config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'gossips#index'
  resources :gossips, only: [:index, :show]
  resources :users, only: [:show]

  # Defines the root path route ("/")

  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'
  get 'welcome/:first_name', to: 'welcome#show', as: 'welcome'
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tag
  has_many :tags, through: :gossip_tag
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: 'User'
    has_and_belongs_to_many :recipients, class_name: 'User'
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :gossip_tag
    has_many :gossips, through: :gossip_tag
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, class_name: 'PrivateMessage', foreign_key: :sender_id
  has_and_belongs_to_many :received_messages, class_name: 'PrivateMessage', join_table: :private_messages_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    def index
        @gossips = Gossip.all
    end

    def show
        @gossip = Gossip.find(params[:id])
      end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def team
    end
  
    def contact
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def show
        @first_name = params[:first_name]
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center page-title">Derniers potins</h1>
    </div>
  </div>
  <div class="row">
    <% @gossips.each do |gossip| %>
      <div class="col-md-12">
        <div class="card gossip-card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to gossip.title, gossip %></h5>
            <p class="card-text"><%= gossip.content %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="text-center"><%= @gossip.title %></h1>
      <p class="text-center"><%= @gossip.created_at.strftime("%B %d, %Y") %></p>
      <table class="table table-bordered table-striped">
        <thead>
          <tr>
            <th>Auteur</th>
            <th>Contenu</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= link_to @gossip.user.first_name, user_path(@gossip.user) %></td>
            <td><%= @gossip.content %></td>
          </tr>
        </tbody>
      </table>
      <div class="text-center">
        <%= link_to "Retour aux potins", gossips_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css', integrity: 'sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk', crossorigin: 'anonymous' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js', integrity: 'sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI', crossorigin: 'anonymous' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js', integrity: 'sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd', crossorigin: 'anonymous' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag 'test', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'contact', media: 'all', 'data-turbolinks-track': 'reload' %>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="<%= root_path %>">Mon site</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="<%= team_path %>">Notre équipe</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= contact_path %>">Contact</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>
  
    </header>

    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center">Contactez-nous</h1>
      <p class="text-center">Nous serons ravis de répondre à toutes vos questions ou préoccupations.</p>
      <form>
        <div class="form-group">
          <label for="name">Nom</label>
          <input type="text" class="form-control" id="name" required>
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" class="form-control" id="email" required>
        </div>
        <div class="form-group">
          <label for="message">Message</label>
          <textarea class="form-control" id="message" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Envoyer</button>
      </form>
    </div>
  </div>
</div>

app/views/static_pages/team.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="text-center">Notre équipe</h1>
      <p class="text-center">Découvrez les personnes talentueuses qui travaillent dur pour vous offrir le meilleur service possible.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="team-member text-center">
        <img src="https://via.placeholder.com/300x300" alt="Nom de la personne" class="img-fluid rounded-circle">
        <h3>Moi</h3>
        <p>Titre du poste</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, magna a fringilla condimentum, felis magna aliquam ante, a rhoncus nisi elit eget velit.</p>
        <ul class="social-links list-inline">
          <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
          <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
          <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="team-member text-center">
        <img src="https://via.placeholder.com/300x300" alt="Nom de la personne" class="img-fluid rounded-circle">
        <h3>Moi</h3>
        <p>Titre du poste</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, magna a fringilla condimentum, felis magna aliquam ante, a rhoncus nisi elit eget velit.</p>
        <ul class="social-links list-inline">
          <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
          <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
          <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="team-member text-center">
        <img src="https://via.placeholder.com/300x300" alt="Nom de la personne" class="img-fluid rounded-circle">
        <h3>Moie</h3>
        <p>Titre du poste</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor, magna a fringilla condimentum, felis magna aliquam ante, a rhoncus nisi elit eget velit.</p>
        <ul class="social-links list-inline">
          <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
          <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
          <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>
<p>Email : <%= @user.email %></p>
<p>Âge : <%= @user.age %> ans</p>
<p>Description : <%= @user.description %></p>

app/views/welcome/show.html.erb
<h1>BIENVENUE <%= @first_name %> !</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>